"""Added repeat fields

Revision ID: 37426ca2c4c2
Revises: 
Create Date: 2025-10-30 17:59:57.463263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37426ca2c4c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('repeat_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('target_day', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_reset', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_column('last_reset')
        batch_op.drop_column('target_day')
        batch_op.drop_column('repeat_type')

    # ### end Alembic commands ###
